---
dist: trusty
language: java

addons:
  apt:
    packages:
      - xsltproc
      - libsaxonhe-java

install:
  - git clone -b master https://github.com/xspec/xspec.git /tmp/xspec

env:
  global:
    - XSPEC=/tmp/xspec/bin/xspec.sh
    - SAXON_CP=/usr/share/java/Saxon-HE.jar

script: "make test XSPEC=$XSPEC"
